# Generated by Django 3.0.8 on 2021-07-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='default_unit',
            field=models.CharField(choices=[('1', 'item'), ('2', 'millilitre'), ('3', 'pint'), ('4', 'teaspoon'), ('5', 'tablespoon'), ('6', 'gram'), ('7', 'ounce'), ('8', 'piece'), ('9', 'pinch'), ('10', 'cup')], default='1', max_length=2),
        ),
    ]
