# Generated by Django 3.0.8 on 2021-08-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_auto_20210802_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='default_unit',
            field=models.CharField(choices=[('1', 'item(s)'), ('2', 'millilitre(s)'), ('3', 'pint(s)'), ('4', 'teaspoon(s)'), ('5', 'tablespoon(s)'), ('6', 'gram(s)'), ('7', 'ounce(s)'), ('8', 'piece(s)'), ('9', 'pinch(s)'), ('10', 'cup(s)'), ('11', 'clove(s)')], default='1', max_length=2),
        ),
    ]
