# Generated by Django 3.0.8 on 2021-08-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_auto_20210805_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='default_unit',
            field=models.CharField(choices=[('1', 'item'), ('2', 'millilitre'), ('3', 'pint'), ('4', 'teaspoon'), ('5', 'tablespoon'), ('6', 'gram'), ('7', 'ounce'), ('8', 'piece'), ('9', 'pinch'), ('10', 'cup'), ('11', 'clove')], default='1', max_length=2),
        ),
    ]
