# Generated by Django 3.0.8 on 2021-07-15 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0002_auto_20210714_1334'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takeaway', models.BooleanField(default=False, verbose_name='Include Takaways')),
                ('takeaway_amount', models.CharField(choices=[('0', 'none'), ('1', 'weekly'), ('2', 'bi-weekly'), ('3', 'once a month'), ('4', 'twice a week')], default='0', max_length=1)),
                ('takeaway_day', models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], default='1', max_length=1)),
                ('friday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='meals.MealCategory', verbose_name='Meal Type - Friday')),
                ('monday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='meals.MealCategory', verbose_name='Meal Type - Monday')),
                ('saturday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='meals.MealCategory', verbose_name='Meal Type - Saturday')),
                ('sunday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='meals.MealCategory', verbose_name='Meal Type - Sunday')),
                ('thursday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='meals.MealCategory', verbose_name='Meal Type - Thursday')),
                ('tuesday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='meals.MealCategory', verbose_name='Meal Type - Tuesday')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wednesday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='meals.MealCategory', verbose_name='Meal Type - Wednesday')),
            ],
        ),
    ]
