# Generated by Django 3.0.8 on 2021-07-27 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210720_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='meal_repeat',
            field=models.PositiveIntegerField(default=7, help_text='Changing this value affects how regularly the planner will select the same meal. Please choose a value between 7 and 28 days. (The default is 7 days (1 week).', validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(28)]),
        ),
    ]
