# Generated by Django 3.0.8 on 2021-08-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_meal_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_setup',
            field=models.BooleanField(default=False),
        ),
    ]
