# Generated by Django 3.0.8 on 2021-07-14 11:55

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('last_planned', models.DateField(null=True, verbose_name='Last Planned')),
                ('cook_time', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('recipe', models.TextField()),
                ('notes', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Meals',
            },
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('unit', models.CharField(choices=[('1', 'unit'), ('2', 'millilitre'), ('3', 'pint'), ('4', 'teaspoon'), ('5', 'tablespoon'), ('6', 'gram'), ('7', 'ounce'), ('8', 'piece'), ('9', 'pinch')], default='1', max_length=1)),
                ('meal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meals.Meal', verbose_name='Related Meal')),
                ('related_ingredient', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ingredients.Ingredient')),
            ],
            options={
                'verbose_name_plural': 'Meal Ingredients',
            },
        ),
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('related_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Meal Categories',
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='related_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='meals.MealCategory'),
        ),
        migrations.AddField(
            model_name='meal',
            name='related_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
