# Generated by Django 3.0.8 on 2021-07-20 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20210720_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealingredient',
            options={'ordering': ['related_ingredient'], 'verbose_name_plural': 'Meal Ingredients'},
        ),
    ]
