# Generated by Django 3.0.8 on 2021-07-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20210720_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='times_planned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
