# Generated by Django 3.0.8 on 2021-07-29 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_meal_times_planned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='notes',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='mealingredient',
            name='meal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='meals.Meal', verbose_name='Related Meal'),
        ),
    ]
