# Generated by Django 3.0.8 on 2021-08-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_auto_20210729_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealingredient',
            name='unit',
        ),
    ]
