# Generated by Django 3.0.8 on 2021-07-28 13:09

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredient_default_unit'),
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekdays',
            name='name',
        ),
        migrations.AddField(
            model_name='weekdays',
            name='meal_date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='weekdays',
            name='meal_day',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='WeekIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('related_ingredient', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ingredients.Ingredient')),
                ('week_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.Week', verbose_name='Related Meal')),
            ],
        ),
    ]
